name: Medical Data App

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x

      - name: Display .NET version
        run: dotnet --version

      - name: Restore dependencies
        run: dotnet restore ExpensesTracker.sln --verbosity detailed

      - name: Build
        run: dotnet build ExpensesTracker.sln --no-restore

      - name: Run Tests
        run: dotnet test ExpensesTracker.sln --no-restore --logger trx --results-directory "TestResults"

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: dotnet-results
          path: TestResults

      - name: Simulate deployment (copy build to folder)
        run: |
          mkdir deployed
          cp -r ExpensesTracker/bin/Release/net6.0/* deployed/
