name: Medical Data App

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: ["6.0.x"]

    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Restore dependencies
        run: dotnet restore ExpensesTracker.sln

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Run Tests
        run: dotnet test --configuration Release --no-restore --logger trx --results-directory "TestResults"

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: TestResults

      - name: Simulate deployment (copy build to folder)
        run: |
          mkdir deployed
          Copy-Item "ExpensesTracker\bin\Release\net6.0-windows\*" -Destination "deployed" -Recurse
